version: "3.7"
services:
  get_iplayer:
    image: marginal/get_iplayer:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: 0 # id -u
        PGID: 0  # id -g
    volumes:
      - iplayer_data:/output
    ports:
      - "1935:1935"
volumes:
  iplayer_data:
    external: true
